apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    app: webserver
  template:
    metadata:
      name: httpd
      labels:
        app: webserver
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80